// Generated by KLFC 1.5.7
// https://github.com/39aldo39/klfc

#include "unimap_trans.h"
#include "action_util.h"
#include "action_layer.h"

enum function_id {
    F_MODIFIER,
};

enum macro_id {
    LIG__percent_,
    LIG__bar_,
    LIG__bracketright_,
    LIG__braceright_,
    LIG__parenright_,
    LIG__exclam_,
    LIG__braceleft_,
    LIG__numbersign_,
    LIG__asciicircum_,
    LIG__at_,
    LIG__parenleft_,
    LIG__dollar_,
    LIG__asciitilde_,
    LIG__ampersand_,
    LIG__plus_,
    LIG__asterisk_,
};

enum modifier_id {
    MOD_SHIFT,
    MOD_SHIFT_L,
    MOD_SHIFT_R,
    MOD_ALTGR,
};

#define AC_FN0 ACTION_MACRO(LIG__percent_)
#define AC_FN1 ACTION_MACRO(LIG__bar_)
#define AC_FN2 ACTION_FUNCTION_OPT(F_MODIFIER, MOD_ALTGR)
#define AC_FN3 ACTION_MACRO(LIG__bracketright_)
#define AC_FN4 ACTION_MACRO(LIG__braceright_)
#define AC_FN5 ACTION_MACRO(LIG__parenright_)
#define AC_FN6 ACTION_MACRO(LIG__exclam_)
#define AC_FN7 ACTION_MACRO(LIG__braceleft_)
#define AC_FN8 ACTION_MACRO(LIG__numbersign_)
#define AC_FN9 ACTION_MACRO(LIG__asciicircum_)
#define AC_FN10 ACTION_MACRO(LIG__at_)
#define AC_FN11 ACTION_MACRO(LIG__parenleft_)
#define AC_FN12 ACTION_MACRO(LIG__dollar_)
#define AC_FN13 ACTION_MACRO(LIG__asciitilde_)
#define AC_FN14 ACTION_MACRO(LIG__ampersand_)
#define AC_FN15 ACTION_MACRO(LIG__plus_)
#define AC_FN16 ACTION_MACRO(LIG__asterisk_)

#ifdef KEYMAP_SECTION_ENABLE
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] PROGMEM = {
#endif
    // None
    [0] = UNIMAP(
               F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
     ESC,       F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9, F10, F11, F12,          PSCR,SLCK,PAUS,         VOLD,VOLU,MUTE,
      NO,  NO,  NO,LALT, FN0,  NO,  NO,  NO,  NO,  NO,RALT, FN1,  NO,JYEN,CAPS,      INS,HOME,PGUP,    NLCK,PSLS,PAST,PMNS,
     TAB,   B,   L,   D,   W,   Z, ESC,QUOT,   F,   O,   U,   J,SCLN,      INS,      DEL, END,PGDN,      P7,  P8,  P9,PPLS,
    BSPC,   N,   R,   T,   S,   G,HOME,   Y,   H,   A,   E,   I,     NUHS,COMM,                          P4,  P5,  P6,PCMM,
    LCTL,NUBS,   X,   M,   C,   Q,   V, END,   K,   P, DOT,MINS,       RO,SLSH,            UP,           P1,  P2,  P3,PENT,
    LALT,LGUI,  NO,MHEN,           SPC,          HENK,KANA, FN2,RGUI, APP,RCTL,     LEFT,DOWN,RGHT,      P0,     PDOT,PEQL
    ),
    // Shift
    [1] = UNIMAP(
              TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,
    TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,          TRNS,TRNS,TRNS,         TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,   5,TRNS,TRNS,TRNS,TRNS, FN3,TRNS,   0,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, APP,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,SLSH,                        TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,PGDN,TRNS,TRNS,TRNS,TRNS,     TRNS,COMM,          TRNS,         TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,          TRNS,          TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,    TRNS,     TRNS,TRNS
    ),
    // AltGr
    [2] = UNIMAP(
              TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,
    TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,          TRNS,TRNS,TRNS,         TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS, FN4,TRNS,TRNS,TRNS,TRNS,RBRC,TRNS, FN5,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS, FN6, FN7,LBRC, FN8, EQL, APP, FN9,FN10,FN11,FN12, GRV,TRNS,     TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
     DEL,   1,FN13, ENT,   0,FN14,PGUP,BSLS,LEFT,  UP,DOWN,RGHT,     TRNS,TRNS,                        TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,   2,   3,   4,   5,FN15,TRNS,FN16,   6,   7,   8,     TRNS,   9,          TRNS,         TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,          TRNS,          TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,    TRNS,     TRNS,TRNS
    ),
};

const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt) {
    switch (id) {
        case LIG__percent_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(5), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__bar_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(BSLS), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__bracketright_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), T(RBRC), RM(), END) :
                   MACRO_NONE;
        case LIG__braceright_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(RBRC), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__parenright_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(0), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__exclam_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(1), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__braceleft_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(LBRC), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__numbersign_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(3), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__asciicircum_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(6), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__at_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(2), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__parenleft_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(9), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__dollar_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(4), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__asciitilde_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(GRV), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__ampersand_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(7), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__plus_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(EQL), U(LSFT), RM(), END) :
                   MACRO_NONE;
        case LIG__asterisk_:
            return record->event.pressed ?
                   MACRO(SM(), CM(), D(LSFT), T(8), U(LSFT), RM(), END) :
                   MACRO_NONE;
    }
    return MACRO_NONE;
}

#define MOD_SHIFT_MASK (MOD_BIT(KC_LSFT)|MOD_BIT(KC_RSFT))

enum vmod_mask {
    VMOD_ALTGR_MASK = 1,
};

uint8_t vmods = 0;

const uint8_t layer_states[] = {
    0x1, // None
    0x3, // Shift
    0x5, // AltGr
    0x7, // Shift+AltGr
};

void action_function(keyrecord_t *record, uint8_t id, uint8_t opt) {
    uint8_t pressed = record->event.pressed;
    switch (id) {
        case F_MODIFIER:
            // Set the new modifier
            switch (opt) {
                case MOD_SHIFT: pressed ? add_key(KC_LSFT) : del_key(KC_LSFT); break;
                case MOD_SHIFT_L: pressed ? add_key(KC_LSFT) : del_key(KC_LSFT); break;
                case MOD_SHIFT_R: pressed ? add_key(KC_RSFT) : del_key(KC_RSFT); break;
                case MOD_ALTGR: pressed ? (vmods |= VMOD_ALTGR_MASK) : (vmods &= ~VMOD_ALTGR_MASK); break;
            }

            // Update the layer
            uint8_t mods = get_mods();
            uint8_t layer_index = 0;
            layer_index |= mods & MOD_SHIFT_MASK ? 1 : 0;
            layer_index |= vmods << 1;
            layer_clear();
            layer_or(layer_states[layer_index]);
            break;
    }
}
